Support for MultiPolygon
mapgears/ol3-google-maps pull request #180
Opened 2017-10-03 04:30 UTC by jacobo

We needed support for this and it seemed relatively easy to add. This works for our specific use case, but I only tested it by directly editing the released `ol3-gm-debug.js`

I'd love to see this support included in the next release so we don't have to maintain a fork or patch, please let me know what I can do next to help this along

2017-10-03 12:15 UTC, adube commented
Thanks a lot for the contribution.  I should be able to review this soon (later this week).  You can poke me if I forget.

2017-10-06 12:05 UTC, adube commented
@jacobo It would be nice if an example in which we demonstrate the support of multi polygons was added.  We could call it "multi-geometries" and only demonstrate polygons (for now).

Would you please add this as part of this PR?  Thanks.

2017-10-20 12:17 UTC, adube commented
@jacobo (in case you missed it) See my last comment.  Thanks.

2017-10-22 03:39 UTC, jacobo commented
thanks, haven't forgotten, currently on paternity leave so this may take a while 👶

2017-10-23 11:18 UTC, adube commented
No problem.  Congratulations, btw :)

2017-11-14 12:16 UTC, LSG8 commented
How to add multilinestring too? I had a look on @jacobo 's code for multipolygon and tried similar things for multilinestring. But it didn't work. I have attached here my modified gm.js as a .txt file
[modified_gm_for_multi_line_n_polygon.js.txt](https://github.com/mapgears/ol3-google-maps/files/1470710/modified_gm_for_multi_line_n_polygon.js.txt)
. Please help me out.

2017-11-14 13:19 UTC, adube commented
@LSG8 Please, provide a separate PR.  This would help seeing what was changed.

2017-11-29 18:42 UTC, jacobo commented
<img width="622" alt="screen shot 2017-11-29 at 10 35 58 am" src="https://user-images.githubusercontent.com/10033/33392781-dec1920e-d4f1-11e7-87ab-285373310cea.png">

I have added an example for multi-polygon to concept.js ( a pinwheel over Ontario and some hand-drawn polygons over the great lakes)

2017-11-29 18:44 UTC, adube commented
That's an excellent idea, i.e. it's better to show this there instead of yet an other example.  Thanks.

I haven't checked: is your code rebased onto master?

2017-11-29 18:45 UTC, adube commented
Nevermind, it's an obvious "yes".  Alright I'll review this PR this week.

2017-11-30 13:37 UTC, adube requested changes
Very minor things to change, then this would be good to merge.  Thanks a lot for the contribution.

2017-11-30 13:37 UTC, adube commented on src/olgm/gm.js
> +    geometry.getCoordinates()[0].forEach(function(coordsArr) {
Instead of a `forEach`, let's use a standard `for` loop as it is faster.

2017-11-30 13:37 UTC, adube commented on src/olgm/gm.js
> +  if (geometry instanceof ol.geom.MultiPolygon) {
Let's move this at the end, i.e.:

1: if line string
2: else if polygons
3: else (multi polygons)

2017-11-30 15:00 UTC, LSG8 commented
@jacobo Can you help me in PR #194 ?

2017-11-30 15:04 UTC, LSG8 commented
@jacobo Can you help me in PR #194 ? I modified the gm.js for multilinestring similar to your modification for multipolygon. But it is not working. I don't get any at the time of `make dist`. But no multilinestring.

2017-11-30 15:05 UTC, LSG8 commented
@jacobo Can you help me in PR #194 ? I modified the gm.js for multilinestring similar to your modification for multipolygon. But it is not working. I don't get any error at the time of `make dist`. But no multilinestring.

2017-11-30 23:51 UTC, jacobo commented
<img width="404" alt="screen shot 2017-11-30 at 3 50 42 pm" src="https://user-images.githubusercontent.com/10033/33461211-49e9ab8a-d5e6-11e7-8f1a-5d53481a6452.png">

multiline string example looks like this ^

2017-11-30 23:56 UTC, jacobo commented
@LSG8 does my implementation of multi line string work for you?

2017-12-01 00:00 UTC, jacobo commented
@adube thanks for your responsiveness, hopefully you don't mind my conflation of 2 features in one PR...

2017-12-01 12:56 UTC, adube commented
@jacobo I don't mind :)  I'll review this today. Thank you very much.

2017-12-01 13:11 UTC, adube approved these changes
Very nice!  Code is clean and the addition to the example made me smile.

2017-12-01 13:13 UTC, merged

2017-12-01 13:25 UTC, LSG8 commented
Thanks @jacobo it is working.

2017-12-02 00:44 UTC, jacobo commented
thanks for the merge @adube any plans to release soon? (I'd like to consume via npm)

2017-12-04 13:02 UTC, adube commented
We could make an other upgrade of OL first, like we've been doing the fast few weeks.  Once done, it would make sense to make a new release.

@bampakoa Are you planning on working for a new upgrade to a new version of OL soon (this week)?  If so, I'd gladly review.  Thanks.

2017-12-04 14:32 UTC, bampakoa commented
@adube I plan to submit a PR this week concerning OL version 4.4.2

2017-12-04 14:34 UTC, adube commented
Excellent, thanks.

2017-12-08 13:20 UTC, adube commented
@jacobo 0.17.0 released: https://www.npmjs.com/package/ol3-google-maps

2017-12-08 18:51 UTC, jacobo commented
Awesome thanks @adube I can confirm it's working!