Handle lengthy and newline character text
mapgears/ol3-google-maps pull request #324
Opened 2021-06-30 01:58 UTC by rajsync

this is related to https://github.com/mapgears/ol3-google-maps/issues/323 issue.
Modified MapLabel.js to handle lengthy text, default canvas created has default width and height. lengthy text with new line character width and height is calculated and canvas width and height is updated.

canvas fill text function doesn't handle newline, hence its handles by calculating text line height and calling multiple fill text

2021-06-30 12:19 UTC, adube requested changes
Thanks for the patch.  I've got a few minor adjustments I'd like you to make.

Also, it would be nice if we could see the fix in action through an example.  Maybe add an additional feature to the "label.js" example that shows how the patch fixes the issue?

Thank you very much and happy coding.

2021-06-30 12:19 UTC, adube commented on src/olgm/gm/MapLabel.js
> +      // ctx.fillText(text, x, y);
Remove the above line that's left commented out

2021-06-30 12:19 UTC, adube commented on src/olgm/gm/MapLabel.js
> +    var words = this.get('text').split('\r\n'),
Use `const` and `let` instead of `var` everywhere.

2021-06-30 12:19 UTC, adube commented on src/olgm/gm/MapLabel.js
> +  wrapText(context, text, x, y) {
Add comment block for method, including the typing of each arguments here and their documentation.

2021-06-30 12:21 UTC, adube commented
@rajsync Oh,I forgot to ask you: after this patch is merged in master, do you need to have a new npm release of olgm being made?  Thanks.

2021-06-30 23:00 UTC, rajsync commented
> @rajsync Oh,I forgot to ask you: after this patch is merged in master, do you need to have a new npm release of olgm being made? Thanks.

@adube Yes, Please do a npm release. Thanks.

2021-07-01 12:23 UTC, adube requested changes
Thanks for the fixes.

Once last detail: would you please run `npm run lint` and fix all issues reported by the linter?  Then we'll be good to go for a merge / release.

Thank you.

2021-07-02 01:16 UTC, rajsync commented
> Thanks for the fixes.
> 
> Once last detail: would you please run `npm run lint` and fix all issues reported by the linter? Then we'll be good to go for a merge / release.
> 
> Thank you.

@adube lint issues are fixed,thanks.

2021-07-02 14:11 UTC, adube approved these changes
Everything's clean.  I've checked the example once again and everything's behaving correctly.

Thanks again for the contribution.  That's really really appreciated.

I'll take care of merging it.

2021-07-02 14:12 UTC, merged

2021-07-02 14:24 UTC, adube commented
@rajsync OLGM v1.7.1 is released on npm.  Thanks for the patch and happy coding.

2021-07-05 01:09 UTC, rajsync commented
> @rajsync OLGM v1.7.1 is released on npm. Thanks for the patch and happy coding.

thanks and appreciate fast response and release @adube