Fix for getStroke issue by checking
mapgears/ol3-google-maps pull request #351
Opened 2023-10-19 00:20 UTC by schagani

style variable if it is array or object

2023-10-19 12:29 UTC, adube requested changes
Thanks for the contribution

Run `npm run lint` and fix the issues raised there.

2023-10-19 12:30 UTC, adube commented on src/olgm/gm.js
> +  if(style instanceof Array){
Use `Array.isArray` instead.

Do so for the equivalent code below.

2023-10-19 23:52 UTC, schagani commented
Changes done. Please review.

2023-10-20 12:13 UTC, adube requested changes
Remove all changes from package-lock.json.

See inline comments below too.

2023-10-20 12:13 UTC, adube commented on src/olgm/gm.js
> +  if (style instanceof Array) {
Replace by Array.isArray

2023-10-20 12:13 UTC, adube commented on src/olgm/gm.js
> +  if (style instanceof Array) {
Replace by Array.isArray

2023-10-20 12:13 UTC, adube commented on src/olgm/gm.js
> +  if (style instanceof Array) {
Replace by Array.isArray

2023-10-20 12:13 UTC, adube commented on src/olgm/herald/Feature.js
> +      if (style instanceof Array) {
Replace by Array.isArray

2023-10-20 12:13 UTC, adube commented on src/olgm/herald/Feature.js
> +      if (style instanceof Array) {
Replace by Array.isArray

2023-10-20 12:13 UTC, adube commented on src/olgm/herald/Feature.js
> +      if (style instanceof Array) {
Replace by Array.isArray

2024-02-26 14:24 UTC, closed without merging

2024-02-26 14:24 UTC, adube commented
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352